import GLOVAR as gl

Import('env')

env_local = env.Clone()

env_local.Prepend(LIBS = ['hsf'])
env_local.Append(LIBPATH = [gl.build_path + '/lib'])

env_local.Append(LIBS = ['unap'])
env_local.Append(LIBPATH = ['/home/export/online1/amd_dev1/guhf/unap/x86Install/lib'])

linker_bin_path = '/home/export/online1/amd_dev1/software/MPICH/bin'

env_local.Program(gl.build_path + '/bin/test', source = 'test.cpp', LINK=linker_bin_path + '/mpicxx')

env_local.Program(gl.build_path + '/bin/ftest', source = 'ftest.f90', LINK=linker_bin_path + '/mpifort')

env_local.Program(gl.build_path + '/bin/regionTest', source = 'regionTest.cpp', LINK=linker_bin_path + '/mpicxx')


