#!/bin/sh
# set -x
CXX=mpiswg++
FC=mpiswgfort453
CLINKER=mpiCC
FLINKER=mpiswgfortran
CXXFLAGS="-g -rdynamic -DLABEL_INT64 -DSCALAR_FLOAT64"
FFLAGS="-g -fcray-pointer -DLABEL_INT64 -DSCALAR_FLOAT64"
LINKFLAGS="-fPIC -g -DLABEL_INT64 -DSCALAR_FLOAT64"

software_home="/home/export/online3/amd_dev1/software"
yaml_home="${software_home}/yaml-cpp/yaml-cpp-0.5.3"
cgns_home="${software_home}/CGNS/CGNS-3.4.0/sw_install"
hdf5_home="${software_home}/HDF5/hdf5-1.8.8"
unat_home="/home/export/online3/amd_dev1/liuhb/unat/install"
boost_home="${software_home}/boost/boost1.69"
parmetis_home="${software_home}/ParMETIS/parmetis-4.0.3/SWInstall_64_64"
utility_home="/home/export/online3/amd_dev1/liuhb/utilities/install/sw64swg++DPOpt"

program_incpath="-I./install/sw64swg++DPOpt/include \
                 -I${yaml_home}/include \
                 -I${cgns_home}/include \
                 -I${hdf5_home}/include \
                 -I${parmetis_home}/include \
                 -I${unat_home}/include \
                 -I${boost_home}/include \
                 -I${utility_home}/include "

program_libpath="-L./install/sw64swg++DPOpt/lib \
                 -L${yaml_home}/lib \
                 -L${cgns_home}/lib \
                 -L${hdf5_home}/lib \
                 -L${parmetis_home}/lib \
                 -L${unat_home}/lib \
                 -L${utility_home}/lib "
program_libs="-lhsf -lUNAT -lutilities -lcgns -lhdf5 -lparmetis -lmetis -lyaml-cpp -lm -lz -ldl -lstdc++"

source_files="test/test.cpp"
object_files="test/test.o"
target="test/test"

# compile
${CXX} ${CXXFLAGS} ${program_incpath} -c ${source_files} -o ${object_files}

# link
${CLINKER} ${LINKFLAGS} ${object_files} -o ${target}  ${program_libpath} ${program_libs}

source_files="test/blk_test.f90"
object_files="test/blk_test.o"
target="test/blk_test"
${FC} ${FFLAGS} ${program_incpath} -c ${source_files} -o ${object_files}

module load sw/compiler/gcc530
${FLINKER} ${LINKFLAGS} ${object_files} -o ${target}  ${program_libpath} ${program_libs}
module unload sw/compiler/gcc530

