from build import add_source_files, cxx_source_files, fortran_source_files

cxxfile = ['mpiWrapper/utilityMpiWrapper.cpp',
            'mpiWrapper/communicationManager/utilityCommunicationManager.cpp',
            'mpiWrapper/communicator/utilityCommunicator.cpp',
            'exceptions/utilityExceptions.cpp',
            'interfaces/utilityInterfaces.cpp']
cfile = ['common/utilityBasicFunction.c']
fortranfile = ['interfaces/utilityInterfaces_module.f90']

add_source_files(cxxfile, cxx_source_files)
add_source_files(cfile, cxx_source_files)
add_source_files(fortranfile, fortran_source_files)