#!/bin/sh
set -x
clang-query  $* -- -w \
    -I/home/export/online3/amd_dev1/software/yaml-cpp/yaml-cpp-0.5.3/include \
    -I/home/export/online3/amd_dev1/software/CGNS/CGNS-3.4.0/sw_install/include \
    -I/home/export/online3/amd_dev1/software/HDF5/hdf5-1.8.8/include \
    -I/home/export/online3/amd_dev1/software/ParMETIS/parmetis-4.0.3/SWInstall_64_64/include \
    -I/home/export/online3/amd_dev1/software/boost/boost1.69/include \
    -I/home/export/online3/amd_dev1/liuhb/unat/install/include \
    -I/home/export/online3/amd_dev1/liuhb/hsf/install/swswg++Int64Float64Opt/include \
    -I/home/export/online3/amd_dev1/software/MPICH/gcc_build/include \
    -I/home/export/online3/amd_dev1/software/gcc-5.4.0/objdir/include/c++/5.4.0 \
    -I/home/export/online3/amd_dev1/software/gcc-5.4.0/objdir/include/c++/5.4.0/x86_64-unknown-linux-gnu \
    -I/home/export/online3/amd_dev1/guhf/utilities/install/linuxmpicxxInt64Float64Opt/include
