from build import add_source_files, cxx_source_files, cslave_source_files
Import('env')

cxxfile = ['funPtr_host.cpp',
           'kernel_spe.cpp',
           'funPtr_data.cpp']

cslavefile = ['kernel_slave.c']

if env['PLATFORM'] == 'sw':
    add_source_files(cxxfile, cxx_source_files)
    add_source_files(cslavefile, cslave_source_files)
