# -*- mode: python -*-

import os
import utils
from build import build_lninclude, build_lib, cxx_source_files, chost_source_files, cslave_source_files, cxxhost_source_files, build_object, fortran_source_files
from build_config import THIRDPARTY_INCS, THIRDPARTY_LIBS

Import('env')

target = 'hsf'

subdirs = Split("""
    field
    interfaces
    iterator
    loadBalancer
    mesh
    meshInfo
    parameter
    patch
    region
    topology
    vector
""")

src_include = list(build_lninclude(env))

for d in subdirs:
    SConscript(os.path.join(d, 'SConscript'), exports=['env', 'src_include'])


objs_all = []

source_files = cxx_source_files

if env['PLATFORM'] == 'sw':
    if env['ATHREAD']:
        # program_inc += []
        objs_all = objs_all + build_object(env,
                                           sources=chost_source_files,
                                           program_inc=THIRDPARTY_INCS,
                                           program_libs=THIRDPARTY_LIBS,
                                           sources_type='host')

        objs_all = objs_all + build_object(env,
                                           sources=cslave_source_files,
                                           program_inc=THIRDPARTY_INCS,
                                           program_libs=THIRDPARTY_LIBS,
                                           sources_type='slave')

        objs_all = objs_all + build_object(env,
                                           sources=cxxhost_source_files,
                                           program_inc=THIRDPARTY_INCS,
                                           program_libs=THIRDPARTY_LIBS)

objs_all = objs_all + build_object(env,
                                   sources=cxx_source_files,
                                   program_inc=THIRDPARTY_INCS,
                                   program_libs=THIRDPARTY_LIBS)

objs_all = objs_all + build_object(env,
                                   sources=fortran_source_files,
                                   program_inc=THIRDPARTY_INCS,
                                   program_libs=THIRDPARTY_LIBS)

build_lib(env,
          target=target,
          sources=objs_all,
          program_inc=THIRDPARTY_INCS,
          program_libs=THIRDPARTY_LIBS)
